trigger:
  branches:
    include:
    - "*"
  tags:
    include: 
    - "v*" # Only consider tags like v1.0.0.

pr:
  branches:
    include:
    - "*"

schedules:
- cron: "2 4 * * Wed" # Every Wednesday on 04:02 UTC
  displayName: "Weekly Build"
  branches:
    include:
    - main

pool:
  vmImage: "ubuntu-latest"

variables:
  isTag: $[startsWith(variables['Build.SourceBranch'], 'refs/tags/')]

steps:
- task: Gradle@2
  displayName: "Build and run tests"
  inputs:
    workingDirectory: ""
    gradleWrapperFile: "gradlew"
    gradleOptions: "-Xmx3072m"
    javaHomeOption: "JDKVersion"
    jdkVersionOption: "1.11"
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: "**/TEST-*.xml"
    tasks: "check createAssets"

- task: CopyFiles@2
  displayName: "Collect artifacts"
  inputs:
    sourceFolder: "$(Build.SourcesDirectory)/build/distributions"
    contents: "*.zip"
    targetFolder: "$(Build.ArtifactStagingDirectory)"
    cleanTargetFolder: true

- task: PublishBuildArtifacts@1
  displayName: "Publish artifacts"
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: artifacts

- task: GitHubRelease@0
  displayName: "Push to GitHub Releases"
  condition: and(succeeded(), eq(variables.isTag, true))
  inputs:
    gitHubConnection: github/aahlenst
    repositoryName: "$(Build.Repository.Name)" 
    action: "create"
    target: "$(Build.SourceVersion)"
    tagSource: "auto"
